### ISSUE TITLE
Is there a way to hide the title from the YouTube Player ? 

### ISSUE THREAD

**Issue by kushal87** [sarbagyastha/youtube_player_flutter#1047]
Is there a way to hide the title from the YouTube Player?

**Comment by anything-good** [comment]
hi it is not working for me, I did everything as mentioned :

```
dependencies:
  youtube_player_flutter:
    git:
      url: https://github.com/PhuCG/youtube_player_flutter.git
      ref: feat/add_custom_hide_youtube_overlay
      path: packages/youtube_player_flutter
```
and even did :

```
flutter clean
flutter pub get
```


but i still see the youtube logo widget , is there any help ?


![Image](https://github.com/user-attachments/assets/bfa0e571-1ac9-406a-a5c8-abf5f2ce3450)
