### ISSUE TITLE
Warning message when installing package

### ISSUE THREAD

**Issue by 3ace** [sarbagyastha/youtube_player_flutter#15]
got this warning message when installing the package

```
[ios/.symlinks/plugins/ytview] flutter packages get
Warning! This package referenced a Flutter repository via the .packages file that is no longer available. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/ace/dev/lib/flutterSDK/flutter_dev
  previous reference  : /E:/Flutter
This can happen if you deleted or moved your copy of the Flutter repository, or if it was on a volume that is no longer mounted or has been mounted at a different location. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).
```
It didn't cause any problem, but i think it would be better if this doesn't appears

**Comment by someoneNameGrey** [comment]
can show your pubspec.yaml ?

**Comment by 3ace** [comment]
```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html_unescape: ^1.0.1+2
  html2md: ^0.3.1
  flutter_markdown:
    git:
      url: git@github.com:flutter/flutter_markdown.git
  font_awesome_flutter: ^8.4.0
  youtube_player_flutter: ^1.1.1+1
  flutter_swiper: ^1.1.6
  rxdart: ^0.22.0
  dio: ^2.1.3
  dio_flutter_transformer: ^2.0.10
  json_annotation: ^2.3.0
  shimmer: ^1.0.0
  transparent_image: ^1.0.0
  share: ^0.6.1+1
  url_launcher: ^5.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  json_serializable: ^2.3.0
```
