### ISSUE TITLE
cannot get video metadata on the init of the widget[BUG]

### ISSUE THREAD

**Issue by mohadel92** [sarbagyastha/youtube_player_flutter#451]
**Describe the bug**
the metadata of the video takes time to show
i cannot depend on it to view the title of the video in the app bar e.g

**To Reproduce**
try to print any meta data related data on init

**Expected behavior**
title and duration should be available

**Comment by godwin-codeprism** [comment]
Added a fix to issue and raised a PR. Until @sarbagyastha approves the PR #459 you can update your pubspec.yml as follows:
```
  youtube_player_flutter:
    git:
      url: https://github.com/codeprismtechnologies/youtube_player_flutter.git
      path: packages/youtube_player_flutter
```
