### ISSUE TITLE
Dependencies need updating: flutter_inappwebview

### ISSUE THREAD

**Issue by jimmyff** [sarbagyastha/youtube_player_flutter#460]
Please update `flutter_inappwebview` to version 5. As you are using version 4, this relies on an old version of uuid (2.0) which is causing problems with newer dart packages.

**Comment by willhaslett** [comment]
Any workaround at present?

**Comment by jimmyff** [comment]
Not that I have found, I tried dependency overrides but had no luck due to breaking changes introduced in newer versions.

Really hoping @sarbagyastha will update the package soon.

**Comment by jimmyff** [comment]
Found a PR with the update: https://github.com/sarbagyastha/youtube_player_flutter/pull/449 - I'm going to test this now

**Comment by MeAtPros** [comment]
@jimmyff when do you plan to implement it?

**Comment by jonatadashi** [comment]
There is a fork for youtube_player_iframe which fixes your problem. 
https://pub.dev/packages/youtube_plyr_iframe

**Comment by subhendukundu** [comment]
@jonatadashi that was my plan, then realized I am using youtube_player_flutter too. So there a need for an upgrade in youtube_player_flutter too :(

**Comment by jimmyff** [comment]
@MeAtPros I'm not implementing the change (I've previously sent PRs but @sarbagyastha doesn't tend to accept them). I'm just utilising the fix PR sent by filipedfs here: https://github.com/sarbagyastha/youtube_player_flutter/pull/449. I've forked his change and using it like so (I suggest you fork your own rather than using mine):

```yaml

dependency_overrides:
  youtube_player_iframe:
    git:
      url: https://github.com/jimmyff/youtube_player_flutter.git
      path: packages/youtube_player_iframe

```

This will tide me over until @sarbagyastha accepts the PRs or updates the package himself.

**Comment by willhaslett** [comment]
fwiw, I recommend using @popshootjapan 's fork (master branch) for now. @filipedfs 's fork (develop branch) does not include updating inappwebview for the `youtube_player_flutter` package (only the iframe package), and when I added that update to its pubspec.yaml, I got build-time errors.

@popshootjapan 's fork ran fine, and includes a bunch of (hopefully sound!?) changes to support null safety.
```yaml
dependency_overrides:
  youtube_player_flutter:
    git:
      url: https://github.com/popshootjapan/youtube_player_flutter.git
      path: packages/youtube_player_flutter
```

@sarbagyastha, with the last commit being 3 months ago, and no apparent movement here, what's the story on maintenance for this repo? Are you looking for community support? I need something that I can count on in production.
