### ISSUE TITLE
[BUG] Every time I install the package my app don't even start

### ISSUE THREAD

**Issue by biel-correa** [sarbagyastha/youtube_player_flutter#471]
**Describe the bug**
Every time I install the package my app don't even start, and only run again when I uninstall it

**To Reproduce**
The only way of reproducing that I can think is by installing this packages
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.4
  http: ^0.12.2
  font_awesome_flutter: ^8.11.0
  shared_preferences: ^2.0.5
  awesome_dialog: ^1.3.2
  jwt_decoder: ^2.0.0
  flutter_pdfview: ^1.0.4
  path_provider: ^2.0.1
  youtube_player_flutter: ^7.0.0+7
  flutter_markdown: ^0.6.1
```

**Expected behavior**
The app should at least start in order to see what mistake I'm making

**Technical Details:**
 - Device: Pixel 2 (emulated)
 - OS: Android
 - Version: 11

**Additional context**
flutter doctor -v
```
[√] Flutter (Channel stable, 2.0.3, on Microsoft Windows [versÃ£o 10.0.19042.867], locale pt-BR)
    • Flutter version 2.0.3 at C:\src\flutter
    • Framework revision 4d7946a68d (13 days ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\Informatica\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = C:\Users\Informatica\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.9.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.9.31105.61
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.54.3)
    • VS Code at C:\Users\Informatica\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.20.0

[√] Connected device (4 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)       • windows       • windows-x64    • Microsoft Windows [versÃ£o 10.0.19042.867]
    • Chrome (web)            • chrome        • web-javascript • Google Chrome 89.0.4389.90
    • Edge (web)              • edge          • web-javascript • Microsoft Edge 88.0.705.50

• No issues found!
```
Full pubspec.yaml
```yaml
name: educpro_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.3.4
  http: ^0.12.2
  font_awesome_flutter: ^8.11.0
  shared_preferences: ^2.0.5
  awesome_dialog: ^1.3.2
  jwt_decoder: ^2.0.0
  flutter_pdfview: ^1.1.0
  path_provider: ^2.0.1
  youtube_player_flutter: ^8.0.0
  flutter_markdown: ^0.6.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/cart.png
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**Comment by Leviosar** [comment]
I think i have a similar problem, when i install `youtube_player_flutter` my release build crashes at start, showing the exception. 

```
E/flutter ( 7737): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
```

At first i thought it was a shared preferences problem, but without `youtube_player_flutter` it runs normally. I'm still trying with different versions of `youtube_player_flutter` to see if some of them works, but 8.00 and 7.x.x don't.

My dependencies:

```
dependencies:
  barcode_flutter: ^1.1.0
  bloc_pattern: ^2.4.0+2
  build_runner: ^1.10.6
  carousel_slider: ^2.3.1
  cep_future: ^0.1.4
  cupertino_icons: ^0.1.2
  dio: ^3.0.9
  expandable: ^3.0.1
  firebase_core: ^0.5.2+1
  firebase_messaging: ^8.0.0-dev.9
  flutter_app_badger: ^1.1.2
  flutter_cupertino_localizations: ^1.0.1
  flutter_launcher_icons: ^0.7.4
  flutter_markdown: ^0.4.0
  flutter_masked_text: ^0.8.0
  flutter_password_strength: ^0.1.4
  font_awesome_flutter: ^8.5.0
  graphql_flutter: ^3.1.0
  http_interceptor: ^0.1.1
  http: ^0.12.0+2
  image_cropper: 1.1.2
  image_picker:
  json_annotation: ^3.0.0
  json_serializable: ^3.2.3
  list_tile_more_customizable: ^1.3.0
  logging: ^0.11.4
  mask_text_input_formatter: ^1.0.5
  open_file: ^2.1.1
  package_info: ^0.4.1
  path_provider: ^1.5.1
  qr_flutter: ^3.0.1
  rxdart: ^0.24.0
  shared_preferences: ^0.5.4+8
  string_splitter: ^0.1.0
  universal_platform: ^0.1.3
  url_launcher: ^5.2.7
  youtube_player_iframe: ^1.2.0
  youtube_player_flutter: ^7.0.0
  webview_flutter: ^0.3.22+1
```

Also, it appears to work perfectly with debug builds for some reason.
