### ISSUE TITLE
[BUG] Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by davamp** [sarbagyastha/youtube_player_flutter#709]
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'
../flutter_inappwebview-5.4.3+7/ios/Classes/Types/UserScript.swift:12:5

**Comment by sarbagyastha** [comment]
The PR with the fix has not made into `flutter_inappwebview`, so for now you can use dependency override in pubspec.yaml to fix the issue.

```yaml
dependency_overrides:   
  flutter_inappwebview:
    git:
      url: https://github.com/VictorUvarov/flutter_inappwebview.git
      ref: ios-16-compile-issue
```
