### ISSUE TITLE
[BUG] WebView not found

### ISSUE THREAD

**Issue by EtcGonza** [sarbagyastha/youtube_player_flutter#774]
**Describe the bug**
Greetings! I'm trying to play youtube videos in my app but I have an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/44512291/214319479-d67394c2-105b-44f6-8f08-dc480969fa85.png)

**To Reproduce**
I have the feeling that this error may be because my dependencies.

```
dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_performance: ^0.8.0+7
  firebase_database: ^9.0.9
  firebase_analytics: ^8.3.4
  firebase_messaging: ^11.2.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.12
  firebase_remote_config: ^2.0.2
  firebase_crashlytics: ^2.8.8

  # Chat dependencies
  stream_chat_flutter: ^5.2.0
  stream_chat_localizations: ^4.0.0
  just_audio: ^0.9.24
  record: ^4.1.1
  flutter_markdown: ^0.6.9+1
  flutter_linkify: ^5.0.2
  simple_url_preview: ^3.0.1
  flutter_vibrate: ^1.3.0
  avatar_glow: ^2.0.2
  audio_wave: ^0.1.4
  demoji: ^2.0.0
  stop_watch_timer: ^1.5.0

  # Others
  provider: ^6.0.3
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.8
  easy_localization: ^3.0.0
  phosphor_flutter: ^1.4.0
  dio: ^4.0.0
  url_launcher: ^6.0.12
  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.2.0
  image_picker: ^0.8.5+3
  infinite_scroll_pagination: ^3.2.0
  timeago: ^3.1.0
  fluttertoast: ^8.0.8
  loader_overlay: ^2.0.10
  duration: ^3.0.8
  flutter_html: ^2.2.1
  device_info: ^2.0.3
  emoji_picker_flutter: ^1.3.0
  uni_links: ^0.5.1
  flutter_switch: ^0.3.2
  tuple: ^2.0.0
  path: ^1.8.0
  share_plus: ^4.0.7
  shimmer: ^2.0.0
  scrollable_positioned_list: ^0.3.2
  file_picker: ^5.2.4
  card_swiper: ^2.0.4
  syncfusion_flutter_charts: ^20.1.58+1
  in_app_review: ^2.0.4
  dio_smart_retry: ^1.2.0
  purchases_flutter: ^4.0.0-rc.1
  jwt_decode: ^0.3.1
  flutter_native_timezone: ^2.0.0
  upgrader: ^4.2.1
  uuid: ^3.0.6
  package_info_plus: ^1.4.2
  reactive_forms: ^13.0.0
  youtube_player_iframe: ^4.0.1
  open_store: ^0.5.0

dependency_overrides:
  webview_flutter: ^4.0.1
  flutter_svg: ^1.0.3
  flutter_math_fork: ^0.6.3
  xml: ^6.1.0
```

I added **webview_flutter** as dependency_overrides because I had this error.
```
Because no versions of youtube_player_iframe match >4.0.1 <5.0.0 and youtube_player_iframe 4.0.1 depends on webview_flutter ^4.0.1, youtube_player_iframe ^4.0.1 requires webview_flutter ^4.0.1.
And because flutter_html 2.2.1 depends on webview_flutter ^2.0.4 and no versions of flutter_html match >2.2.1 <3.0.0, youtube_player_iframe ^4.0.1 is incompatible with flutter_html ^2.2.1.
So, because ch_platform_mobile depends on both flutter_html ^2.2.1 and youtube_player_iframe ^4.0.1, version solving failed.
```

And adding the webview_flutter to overrides solved it. Actually I created a clear new project and add in the pubspec only these dependencies

```
dependencies:
  flutter:
    sdk: flutter
  youtube_player_iframe: ^4.0.1
  flutter_html: ^2.2.1

dependency_overrides:
  webview_flutter: ^4.0.1
```

I created this new project just to be sure that the original error isn't it because the override... In this new project I did't have the original error. So looks like the error of the screens isn't because I overrided the dependency.
